use_frameworks!

platform :ios, '14.5'

target 'AutoSelfieLibChallenge_Example' do
  pod 'AutoSelfieLibChallenge', :path => '../'

  target 'AutoSelfieLibChallenge_Tests' do
    # inherit! :search_paths
  end
  
end
