use_frameworks!

platform :ios, '14.0'

target 'AutoSelfieIOSLibChallenge_Example' do
  pod 'AutoSelfieIOSLibChallenge', :path => '../'

  target 'AutoSelfieIOSLibChallenge_Tests' do
    inherit! :search_paths
  end
  
end
