osx_image: xcode12.5
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
  - bundle install
  - pod install --project-directory=Example
script:
  - fastlane ios test
  - pod lib lint --allow-warnings
