osx_image: xcode12.5
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install bundler:2.2.20
  - bundle install
  - pod install --project-directory=Example
script:
  - bundle exec fastlane ios test
  - pod lib lint --allow-warnings
