default_platform(:ios)

platform :ios do
  xcworkspace = "Example/AutoSelfieLibChallenge.xcworkspace"
  test_scheme = "AutoSelfieLibChallenge-Example"

  desc "Run all framework tests"
    lane :test do
      run_tests(workspace: xcworkspace, scheme: test_scheme)
    end

end
